version: '3.9'

services:
  frontend:
    container_name: my_frontend
    build: ./frontend
    ports:
      - "8181:80"

  backend:
    container_name: my_backend
    build: ./backend
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command:
      - "--nginx.scrape-uri=http://my_frontend/nginx_status"
    ports:
      - "9113:9113"
    depends_on:
      - frontend
